### ISSUE TITLE
LazyTree 과제 테스트시 메모리 초과 에러가 나서 질문 드립니다.

### ISSUE THREAD

**Issue by ik1ne** [snu-sf-class/pp201902#17]
과제 LazyTree 구현 후 실행시 다음과 같은 출력이 나오면서 프로그램이 죽어서 질문을 드립니다.
```
pp201902.hw3.Data.Node@6442b0a6
pp201902.hw3.Data.Node@60f82f98
Elapsed time: 0ms
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
```

혹시 과제 제출 서버와 java/scala 버전이 달라서 발생하는 문제가 아닌가 싶어서 과제 제출 서버의 java/scala 버전에 대해서 질문드립니다.

제 환경은 다음과 같습니다.
```shell
$  scala -version
Scala code runner version 2.13.1 -- Copyright 2002-2019, LAMP/EPFL and Lightbend, Inc.
$  java --version
openjdk 12.0.2 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)
```

**Comment by petrosyh** [comment]
제출서버가 조만간 열릴텐데, 그 서버와 비교를 해보시는게 좋을 것 같습니다.
저희쪽에서도 update가 생기면 ping드리겠습니다.

**Comment by petrosyh** [comment]
@ik1ne 저희가 준 예제의 height를 20으로 설정하고 테스트를 해보시기 바랍니다.
즉, height = 1에 대한 sum과 height = 20에 대한 sum을 구하게 되는 것입니다.

**Comment by ik1ne** [comment]
@petrosyh 지금 제출서버에 업로드해보니 FAIL이 떠서, 아마도 제 구현이 잘못된게 아닌가 싶습니다. 일단 로컬에서 19까지는 잘 돌아가기는 합니다.
