### ISSUE TITLE
run.sh은 잘 돌아가는데 서버에 업로드시 계속 FAIL이 떠서 질문드립니다.

### ISSUE THREAD

**Issue by ik1ne** [snu-sf-class/pp201902#28]
로컬에서 run.sh 실행시 1초 안에 4개 줄이 출력되면서 정상적으로 종료되는 반면 서버에 업로드시 다음과 같은 메시지가 나오면서 FAIL이 뜹니다.
```
>>Default test for problem 1
>>Score
0
>>Message
[[FAIL]]
```
기존에는 테스트 케이스별로 [[SUCCESS/FAIL]]이 나왔던거 같은데 이번에는 한줄밖에 안나와있어서 질문드립니다.
FAIL이 뜨는게 정상인가요 아니면 4개중에서 1개라도 틀려서 FAIL이 뜨는건가요?

**Comment by Dongjoo-Kim** [comment]
fail이 하나만 뜨는 경우는 아직 제출기한이 지나지 않아 컴파일 여부를 확인할 수 있는지 확인할 수 있는 간단한 케이스에 대한 결과입니다.
실제 채점 결과는 제출 기한이 지난 후 공개될 것입니다.

또한 주어진 스크립트의 경우는 단순히 함수의 수행 시간만을 측정하고 있으므로 구현이 잘 못 되었다면 제출 시 fail이 뜰 수 있습니다.

**Comment by aloha-connor** [comment]
계산되는 값을 확인해보니 h = 12일 때 sumH의 결과가 overflow가 나면서 값이 틀리게 되는데 혹시 이 부분때문에 서버에서 fail이 뜨는 건 아닌지 확인 부탁드려도 될까요?? 저도 비슷하게 서버에서 fail이 떠서요

**Comment by HurSungYun** [comment]
@Dongjoo-Kim 작성자분과 같은 결과가 출력되는 경우라면,

함수의 수행시간을 초과하여 FAIL 이 뜬 것이라고 판단하면 되는 건가요?

아니면

간단한 케이스에 대해 컴파일이 잘 되었다고 판단하면 되는 건가요?

**Comment by Dongjoo-Kim** [comment]
@ik1ne @Connor-Wapi @HurSungYun 컴파일 확인용 채점케이스에 오타가 있어 수정하였습니다. 지금 제출한 파일들에 대해 재채점을 하고 있는 상황으로 점수가 공개된 후에도 이상이 있다면 알려주시길 바랍니다. 감사합니다.

**Comment by ik1ne** [comment]
다시 업로드해보니 SUCCESS 메시지가 출력됬습니다. 감사합니다.
