### ISSUE TITLE
Project Rmk의 Env관련 질문드립니다.

### ISSUE THREAD

**Issue by ik1ne** [snu-sf-class/pp201902#33]
다음 식의 실행결과가 1이 나오는지, 아니면 ExceptionMsg를 출력하는지 알고싶습니다.
```(let ((val x 1)) (let ((val y (rmk (val a 1)))) (rfd y x)))```
즉, record 내에서 변수를 찾지 못하면 에러를 띄워야 하는지 아니면 변수가 선언된 환경도 확인해야하는지 궁금합니다.

**Comment by petrosyh** [comment]
record 내에서 변수를 찾지 못하면 에러를 띄우시면 될 것 같습니다.
(rfd E x)는 E가 record일때, 그 record에 있는 x라는 항목을 찾아서 계산하는 것이라고 생각하면 좋을 것 같습니다.
