### ISSUE TITLE
[Project] 제출 방법 질문드립니다.

### ISSUE THREAD

**Issue by ik1ne** [snu-sf-class/pp201902#36]
프로젝트 스펙 문서에는 따로 어떻게 제출하라고 안나와있는데요, 이번에도 game 과제 제출때처럼 pp@sf.snu.ac.kr 로 메일로 보내면 되나요?

**Comment by petrosyh** [comment]
기말고사 때문에 좀 늦어졌는데, 곧 제출서버를 열어드릴 예정입니다.
