### ISSUE TITLE
Project 관련 질문드립니다

### ISSUE THREAD

**Issue by 5209410** [snu-sf-class/pp201902#38]
안녕하세요 과제 구현 중 명시되지 않은 부분에 대해서 어떻게 처리하는 것이 맞는지 문의드리려고 합니다.

1. function call (app E E*) 에서 E는 EName으로 정해져있는건지 아니면 다른 타입일 수도 있는지 질문드리고 싶습니다

그러니까 예를 들어 (app f 2 3)이 있을 때 f는 EName이라고 보면 되나요?

2. function call하면서 인자를 대입할 때 단순히 적은 순서대로 들어가는지 아니면 다른 규칙이 있는지 궁금합니다.

그러니까 예를 들어 (let (def f (x y) (+ x y))(app f 2 3))에서 자동적으로 순서에 따라 x=2, y=3이 대입되는지 아니면 다른 규칙이 있는지 질문드리고 싶습니다.
 
감사합니다.

**Comment by petrosyh** [comment]
1. 정해져있지 않습니다. 그리고 어떤 expression인지가 중요한 것이 아니라, E의 계산 결과가 VDef라는 것이 중요한 것입니다. VDef가 아니라면 에러를 내주시거나 어떤식으로 처리하든 상관 없습니다.

2. 그 순서대로 대입한다고 생각하시면 되겠습니다.
