### ISSUE TITLE
Project 컴파일 관련 질문드립니다

### ISSUE THREAD

**Issue by 5209410** [snu-sf-class/pp201902#40]
제출서버에 컴파일은 성공적으로 되었으나,

Test 결과를 확인하기 위해 직접 컴파일하려고 하면 
Object XXX is not a member of package pp201902.project 
라는 에러가 수십 줄 출력됩니다

Path 문제인 것으로 짐작되지만 어떻게 경로를 고쳐야하는지 등 잘 모르겠어서 질문드립니다..

**Comment by Dongjoo-Kim** [comment]
파일 구조를 변경하시지 않으셨다면 compile.sh과 run.sh로 REPL을 실행시킬 수 있을 것입니다.
이를 실행시킨 후 string을 넣으시면 계산 결과를 알 수 있을 것입니다.

예제 testcase는 src/test/scala/Test.scala를 보시면 될 것 같습니다.

에러가 계속 발생하신다면 메일 후 연구실로 찾아오시거나 문서구조 및 에러 사진을 보내주시면 도움을 드리겠습니다.
